### ISSUE TITLE
Move App from Heroku to another hosting service

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestia-rml-demo#17]
Before my internship ends in September, we need to move the app from my personal Heroku account to another hosting service.

**Comment by andreaskundig** [comment]
The new file netlify.toml configures a netlify build.

It's deployed to https://hestia-rml.netlify.app/ whenever the **netlify** branch is pushed.

The netlify site is configured here: https://app.netlify.com/sites/hestia-rml/overview

**Comment by andreaskundig** [comment]
Valentin tested it and says it works.
