### ISSUE TITLE
Change code editor component

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestia-rml-demo#45]
Might want to use another editor, like Ace. Looks like it has better performance than Prism.
https://ace.c9.io/

Vue wrapper:
https://www.npmjs.com/package/vue2-ace-editor

How to use with Nuxt:
https://github.com/chairuosen/vue2-ace-editor/issues/66

Other options to look at:
Monaco
https://github.com/microsoft/monaco-editor
https://www.npmjs.com/package/vue-monaco

**Comment by andreaskundig** [comment]
Monaco doesn't work well on mobile browsers, I'll go with ace
https://github.com/Microsoft/monaco-editor/issues/246
