### ISSUE TITLE
configure unzipit to use workers

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestia-rml-demo#56]
We're not using the unzipit worker.

Security Error: Content at https://hestia-rml.herokuapp.com/twitter-advertisers may not load data from https://unpkg.com/unzipit@1.3.5/dist/unzipit-worker.module.js.

*utils/unzip.js* configures the worker.
Maybe we can solve the problem by referring to the worker file in the node_modules our server, by importing it. We might be able to find it's adress using webpack's require.resolve.

**Comment by valentinoli** [comment]
The worker is only supported in Node.js
https://github.com/greggman/unzipit/issues/21

**Comment by valentinoli** [comment]
Apparently, I was wrong. We should be using the worker.module.js file

**Comment by andreaskundig** [comment]
Unzipit's author says it's documented [here](https://github.com/greggman/unzipit#with-workers)

**Comment by valentinoli** [comment]
https://github.com/greggman/unzipit/issues/21#issuecomment-910395695
