### ISSUE TITLE
SPARQL query not editable anymore

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestia-rml-demo#83]
Procedure
- Select a SPARQL query (e.g. twitter-advertisers, main-05)
- Edit the query (e.g. change "group" to "boston")
- Click the "Run query" button

Expected behavior:
The result of the edited query is shown in the table

Observed behavior:
The result of the unedited query is shown in the table

This bug has probably been introduced with the new editor (ace), because this bug does not happen in an older version

**Comment by valentinoli** [comment]
Thanks for fixing. The bug must have been accidentally introduced

**Comment by andreaskundig** [comment]
I only just saw that now. I introduced that bug. I remember wondering why there ways a '.sync' there and removed it. Now I know.

Thanks for fixing that.
